name 'cracker'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cracker'
long_description 'Installs/Configures cracker'
version '0.1.0'
